
services:
  mysql:
    image: mysql:latest
    container_name: MySql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: AlgumaSenha              # Defina a senha do root
      MYSQL_DATABASE: NomeDoBancoInicial
    ports:
      - "3306:3306"                                 # Mapeia a porta 3306 do contêiner para a máquina host
    volumes:
      - /caminho/no/host:/caminho/no/container      # Monta o diretório local para persistência de dados
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge
